# Generates a C++ translation unit embedding a binary file as a byte array.
# Used to bake networks/default.nnue into the engine binary. A generated array is used
# instead of `.incbin` assembly because the release builds span Mach-O (Clang), ELF (GCC)
# and PE (LLVM-MinGW cross) — section directives differ per format, byte arrays don't.
#
# Usage: cmake -DIN=<binary file> -DOUT=<generated .cpp> -P embed_file.cmake
# Defines: g_default_net (64-byte aligned), g_default_net_size.

if(NOT DEFINED IN OR NOT DEFINED OUT)
    message(FATAL_ERROR "embed_file.cmake needs -DIN=<file> -DOUT=<cpp>")
endif()

file(READ "${IN}" HEX_DATA HEX)
string(LENGTH "${HEX_DATA}" HEX_LEN)
math(EXPR BYTE_LEN "${HEX_LEN} / 2")

# "0xAB," per byte, newline every 32 bytes to keep the file editor/compiler friendly.
string(REGEX REPLACE "(..)" "0x\\1," BYTES "${HEX_DATA}")
string(REGEX REPLACE "((0x..,){32})" "\\1\n" BYTES "${BYTES}")

file(WRITE "${OUT}" "// Generated by cmake/embed_file.cmake from ${IN} — do not edit.
#include <cstddef>

extern const unsigned char g_default_net[];
extern const size_t        g_default_net_size;

alignas(64) const unsigned char g_default_net[${BYTE_LEN}] = {
${BYTES}
};
const size_t g_default_net_size = ${BYTE_LEN};
")

message(STATUS "embedded ${IN} (${BYTE_LEN} bytes) -> ${OUT}")
